export const newsItems = [
  {
    id: 1,
    title: "University Announces New AI Research Center",
    category: "Academics",
    excerpt: "The new center will focus on machine learning and data science, fostering collaboration between departments.",
    imageId: "news-1",
    date: "2024-10-26",
  },
  {
    id: 2,
    title: "Basketball Team Wins Championship",
    category: "Sports",
    excerpt: "A thrilling final match concludes with a victory for the home team, securing the national title.",
    imageId: "news-4",
    date: "2024-10-25",
  },
  {
    id: 3,
    title: "Student Art Exhibition Opens at Gallery",
    category: "Arts & Culture",
    excerpt: "Featuring works from over 50 student artists, the exhibition explores themes of identity and modernity.",
    imageId: "news-2",
    date: "2024-10-24",
  },
  {
    id: 4,
    title: "Career Fair Connects Students with Top Employers",
    category: "Campus Life",
    excerpt: "Hundreds of students attended the annual career fair, with major tech and finance companies recruiting.",
    imageId: "news-3",
    date: "2024-10-23",
  },
   {
    id: 5,
    title: "Volunteering Initiative for Local Community Launched",
    category: "Campus Life",
    excerpt: "A new student-led program aims to provide support and resources to local shelters and community centers.",
    imageId: "news-1",
    date: "2024-10-22",
  },
  {
    id: 6,
    title: "Debate Club Hosts Panel on Modern Politics",
    category: "Academics",
    excerpt: "Experts and students engaged in a lively discussion on the future of global political landscapes.",
    imageId: "news-2",
    date: "2024-10-21",
  },
];
